### PR TITLE
[Medium] Add extra directory when linking scoped package

### LINKED ISSUE #934: "npm link" fails to link correctly (may be an npm v7 issue)
When I use `npm link` in a package (with scope), e.g. `@foo/bar` it generates a shortcut link points to a non-existing place.

So if I look in 

```shell
ls -l /Users/XXXXX/.volta/tools/image/packages/@foo/bar/lib/node_modules/@bar
```

I get `amazon-product-catalog-client -> ../../../../../../../../code/mono/packages/XXX/bar` which is _almost_ fine, except that it has too many `../`-s.

Given that there's no open issue on this, and given that I'm using npm v7 (with Node v15.7), then I'm guessing the issue is compatibility with npm v7.

### PR DESCRIPTION
**Pull request by charlespierce**
Closes #934 

Info
-----
* With npm 7, when we run `npm link` it uses a relative path to link the local directory to the global directory.
* Since we link into a temp directory and then `rename` to the final `tools/images` directory, we need to make sure that the temp directory has the same level of nesting as the final directory, so that relative symlinks work correctly.
* When linking a package that has a scope, the final directory includes an extra level of nesting, from `@scope/package`, so we need to account for that when creating the temp directory.

Changes
-----
* Updated the install executor and helper struct (`DirectInstall`) to support including the name if available.
* Updated `setup_staging_directory` to handle the case when an extra layer of nesting is required.
* Connected the argument parser to correctly fetch the name and pass it through when `npm link` is run, ensuring that scoped packages are handled correctly.

Tested
-----
* Local testing confirmed that running `npm link` in a scoped package sets up the relative symlink correctly.
* Local testing to ensure that the non-scoped packages are still handled correctly.

### CODE REVIEW

File: crates/volta-core/src/tool/package/mod.rs [hunk 1]
```diff
@@ -35,7 +35,7 @@ pub struct Package {
 
 impl Package {
     pub fn new(name: String, version: VersionSpec) -> Fallible<Self> {
-        let staging = setup_staging_directory(PackageManager::Npm)?;
+        let staging = setup_staging_directory(PackageManager::Npm, false /* needs_scope */)?;
```
Comment (chriskrycho) [inline crates/volta-core/src/tool/package/mod.rs:38]: The need for the comment is… suggestive… of the high utility we'd get from refactoring this to use an enum (_a la_ [Booleans and Enums](https://thoughtbot.com/blog/booleans-and-enums)):

```rust
#[derive(PartialEq)]
enum NeedsScope {
    Yes,
    No,
}
```

Because of this kind of readability/comprehensibility issue, I've actually gotten to the point where I'll just straight-up introduce new boolean enums anywhere it helps. It makes a *very* small difference in the size of the compiled binary and otherwise no difference perf-wise, so it seems very much worth the tradeoff to me.

```suggestion
        let staging = setup_staging_directory(PackageManager::Npm, NeedsScope::No)?;
```

File: crates/volta-core/src/run/parser.rs [hunk 2]
```diff
@@ -345,12 +345,15 @@ pub struct LinkArgs<'a> {
 }
 
 impl<'a> LinkArgs<'a> {
-    pub fn executor(self, platform: Platform) -> Fallible<Executor> {
+    pub fn executor(self, platform: Platform, project_name: Option<String>) -> Fallible<Executor> {
         if self.tools.is_empty() {
             // If no tools are specified, then this is a bare link command, linking the current
             // project as a global package. We treat this exactly like a global install
```
Comment (chriskrycho) [inline crates/volta-core/src/run/parser.rs:351]: Does this comment still actually hold without modification? Also, can we add to it slightly to explain what we're doing with the `name` handling? At first read, it wasn't obvious which piece of the new code it meant, exactly (because it refers to the old code!) and it *doesn't* explain the `name` handling, so I was left slightly scratching my head.

File: crates/volta-core/src/tool/package/mod.rs [hunk 3]
```diff
@@ -126,13 +126,28 @@ impl Display for Package {
 pub struct DirectInstall {
     staging: TempDir,
     manager: PackageManager,
+    name: Option<String>,
```
Comment (chriskrycho) [inline crates/volta-core/src/tool/package/mod.rs:129]: If I've followed the writeup and the PR correctly, this is the *package* name for the installation? Could we go with that instead, or does it seem clear enough once you have the context of the module loaded up? (I'm happy to defer, here; I do *not* have the context loaded up here, and I'm a big fan of the shortest name possible to get the point across.)

File: crates/volta-core/src/tool/package/mod.rs [hunk 4]
```diff
@@ -211,17 +230,22 @@ impl InPlaceUpgrade {
...
-fn setup_staging_directory(manager: PackageManager) -> Fallible<TempDir> {
+fn setup_staging_directory(manager: PackageManager, needs_scope: bool) -> Fallible<TempDir> {
     // Workaround to ensure relative symlinks continue to work.
     // The final installed location of packages is:
     //      $VOLTA_HOME/tools/image/packages/{name}/
     // To ensure that the temp directory has the same amount of nesting, we use:
     //      $VOLTA_HOME/tmp/image/packages/{tempdir}/
     // This way any relative symlinks will have the same amount of nesting and will remain valid
     // even when the directory is persisted.
+    // We also need to handle the case when the linked package has a scope, which requires another
```
Comment (chriskrycho) [inline crates/volta-core/src/tool/package/mod.rs:241]: It's workarounds all the way down. 😂

File: crates/volta-core/src/tool/package/mod.rs [hunk 5]
```diff
@@ -126,13 +126,28 @@ impl Display for Package {
 pub struct DirectInstall {
     staging: TempDir,
     manager: PackageManager,
+    name: Option<String>,
 }
 
 impl DirectInstall {
     pub fn new(manager: PackageManager) -> Fallible<Self> {
-        let staging = setup_staging_directory(manager)?;
+        let staging = setup_staging_directory(manager, false /* needs_scope */)?;
```
Comment (chriskrycho) [inline crates/volta-core/src/tool/package/mod.rs:134]:
```suggestion
        let staging = setup_staging_directory(manager, NeedsScope::No)?;
```

File: crates/volta-core/src/tool/package/mod.rs [hunk 6]
```diff
@@ -126,13 +126,28 @@ impl Display for Package {
...
-        Ok(DirectInstall { staging, manager })
+        Ok(DirectInstall {
+            staging,
+            manager,
+            name: None,
+        })
+    }
+
+    pub fn with_name(manager: PackageManager, name: String) -> Fallible<Self> {
+        let staging = setup_staging_directory(manager, name.contains('/'))?;
```
Comment (chriskrycho) [inline crates/volta-core/src/tool/package/mod.rs:144]:
```suggestion
        let staging = setup_staging_directory(manager, name.contains('/').into())?;
```

File: crates/volta-core/src/tool/package/mod.rs [hunk 7]
```diff
@@ -211,17 +230,22 @@ impl InPlaceUpgrade {
 
 /// Create the temporary staging directory we will use to install and ensure expected
 /// subdirectories exist within it
-fn setup_staging_directory(manager: PackageManager) -> Fallible<TempDir> {
+fn setup_staging_directory(manager: PackageManager, needs_scope: bool) -> Fallible<TempDir> {
```
Comment (chriskrycho) [inline crates/volta-core/src/tool/package/mod.rs:233]:
```suggestion
fn setup_staging_directory(manager: PackageManager, needs_scope: NeedsScope) -> Fallible<TempDir> {
```

File: crates/volta-core/src/tool/package/mod.rs [hunk 8]
```diff
@@ -211,17 +230,22 @@ impl InPlaceUpgrade {
...
     // To ensure that the temp directory has the same amount of nesting, we use:
     //      $VOLTA_HOME/tmp/image/packages/{tempdir}/
     // This way any relative symlinks will have the same amount of nesting and will remain valid
     // even when the directory is persisted.
+    // We also need to handle the case when the linked package has a scope, which requires another
+    // level of nesting
     let mut staging_root = volta_home()?.tmp_dir().to_owned();
     staging_root.push("image");
     staging_root.push("packages");
+    if needs_scope {
```
Comment (chriskrycho) [inline crates/volta-core/src/tool/package/mod.rs:246]:
```suggestion
    if needs_scope == NeedsScope::Yes {
```

**Review by chriskrycho — CHANGES_REQUESTED** [review]
Implementation makes good sense to me! I did notice one thing which I think would be really helpful to tweak for long-term maintainability, but no fundamental issues here!

File: crates/volta-core/src/tool/package/mod.rs (hunk 6 above)
Comment (chriskrycho) [reply crates/volta-core/src/tool/package/mod.rs:144]: Alternatively:

```suggestion
        let staging = setup_staging_directory(manager, NeedsScope::from(name.contains('/')))?;
```

File: crates/volta-core/src/run/parser.rs (hunk 2 above)
Comment (charlespierce) [reply crates/volta-core/src/run/parser.rs:351]: That's a good call out, I'll update it to reflect that we treat it like a global install that we definitely know the name up-front (global installs can be from an arbitrarily named tarball or git link, so we don't always know the name a priori).

File: crates/volta-core/src/tool/package/mod.rs (hunk 1 above)
Comment (charlespierce) [reply crates/volta-core/src/tool/package/mod.rs:38]: I definitely went back and forth on this, I _didn't_ like using a boolean, so yeah I think a boolean Enum is worth it!

File: crates/volta-core/src/tool/package/mod.rs (hunk 4 above)
Comment (charlespierce) [reply crates/volta-core/src/tool/package/mod.rs:241]: That's the truth!

File: crates/volta-core/src/tool/package/mod.rs (hunk 3 above)
Comment (charlespierce) [reply crates/volta-core/src/tool/package/mod.rs:129]: It is the package name, yeah. I think it's pretty clear when you have the context, that we're talking about installing a single package, so this is the name. That said, I'll add a comment about how we don't always know the name up-front which should help make it more clear.

Comment (chriskrycho) [reply crates/volta-core/src/tool/package/mod.rs:129]: That makes sense, so I think a comment will close the gap nicely. Thank you!

**Comment by charlespierce** [comment]
Updated with some more comments + a boolean Enum

**Review by chriskrycho — APPROVED** [review]
Thanks for the iteration!
