### PR TITLE
Ensure download directory exists for tarballs

### LINKED ISSUE #538: Installing scoped packages is broken
Someone ran into this issue when trying to install a scoped package from an internal registry, and I was able to repro:

```
$ volta install @linkedin/rb-status --verbose
[verbose] No custom hooks found
[verbose] Running command: `"npm" "view" "--json" "@linkedin/rb-status@latest"`
[verbose] [parsed package metadata (single)]
NpmViewData { name: "@linkedin/rb-status", version: Version { major: 0, minor: 7, patch: 12, pre: [], build: [] }, dist: RawDistInfo { shasum: "6e73f0d545d3a29533c3aceab14c0d4508d96675", tarball: "http://dev-artifactory.corp.linkedin.com:8081/artifactory/api/npm/npm-internal/com/linkedin/rb-status/rb-status/0.7.12/linkedin-rb-status-0.7.12.tgz" }, dist_tags: RawPackageDistTags { latest: Version { major: 0, minor: 7, patch: 12, pre: [], build: [] }, beta: None } }
[verbose] Found @linkedin/rb-status latest version (0.7.12) from http://dev-artifactory.corp.linkedin.com:8081/artifactory/api/npm/npm-internal/com/linkedin/rb-status/rb-status/0.7.12/linkedin-rb-status-0.7.12.tgz
[verbose] Downloading @linkedin/rb-status@0.7.12 from http://dev-artifactory.corp.linkedin.com:8081/artifactory/api/npm/npm-internal/com/linkedin/rb-status/rb-status/0.7.12/linkedin-rb-status-0.7.12.tgz
error: Could not download @linkedin/rb-status@0.7.12
from http://dev-artifactory.corp.linkedin.com:8081/artifactory/api/npm/npm-internal/com/linkedin/rb-status/rb-status/0.7.12/linkedin-rb-status-0.7.12.tgz

Please verify your internet connection and ensure the correct version is specified.
[verbose] Error cause: No such file or directory (os error 2)
Error details written to /Users/mistewar/.volta/log/volta-error-2019-08-23_12_01_56.182.log
```

I found that Tarball is attempting to unpack the package tarball to a path that doesn't exist. Running `mkdir ~/.volta/tools/inventory/packages/@linkedin/` fixed the issue in this case.

We should ensure that the directory exists before unpacking.

### PR DESCRIPTION
**Pull request by mikrostew**
Fixes #538.

This ensures that the directory exists before trying to unpack the tarball there.

Additional cleanup: I moved the `ensure_containing_dir_exists` function into a new `fs-utils` crate. There are some other functions that could be moved there, but I didn't want to go down that hole for this PR.

When there is an error (I made the parent dir read-only for this), we get the error message from the OS:

```
$ ./target/debug/volta install @wdio/cli --verbose
[verbose] No custom hooks found
[verbose] Running command: `"npm" "view" "--json" "@wdio/cli@latest"`
[verbose] [parsed package metadata (single)]
NpmViewData { name: "@wdio/cli", version: Version { major: 5, minor: 12, patch: 5, pre: [], build: [] }, dist: RawDistInfo { shasum: "f4121b0d7682f67431521b83aa213c23128341a2", tarball: "https://registry.npmjs.org/@wdio/cli/-/cli-5.12.5.tgz" }, dist_tags: RawPackageDistTags { latest: Version { major: 5, minor: 12, patch: 5, pre: [], build: [] }, beta: None } }
[verbose] Found @wdio/cli latest version (5.12.5) from https://registry.npmjs.org/@wdio/cli/-/cli-5.12.5.tgz
[verbose] Downloading @wdio/cli@5.12.5 from https://registry.npmjs.org/@wdio/cli/-/cli-5.12.5.tgz, to /Users/mistewar/.volta/tools/inventory/packages/@wdio/cli-5.12.5.tgz
error: Could not download @wdio/cli@5.12.5
from https://registry.npmjs.org/@wdio/cli/-/cli-5.12.5.tgz

Please verify your internet connection and ensure the correct version is specified.
[verbose] Error cause: Permission denied (os error 13)
Error details written to /Users/mistewar/.volta/log/volta-error-2019-08-27_15_23_26.598.log
```

### CODE REVIEW

File: crates/archive/src/tarball.rs [hunk 1]
```diff
@@ -30,6 +30,40 @@ pub struct Tarball {
...
+
+/// Thrown when the containing directory could not be determined
+#[derive(Fail, Debug)]
+#[fail(display = "Could not create directory {}", dir)]
+struct CreateDirError {
+    dir: String,
+}
+
+/// This creates the parent directory of the input path, assuming the input path is a file.
+pub fn ensure_containing_dir_exists<P: AsRef<Path>>(path: &P) -> Result<(), failure::Error> {
```
Comment (charlespierce) [inline crates/archive/src/tarball.rs]: Is it possible to make this call in `volta-core`, maybe immediately before calling unpack? As opposed to duplicating this function in a different crate?

Comment (mikrostew) [reply crates/archive/src/tarball.rs]: I was actually planning to extract this to a new `fs-utils` crate, so it could be used by any of the crates.

Comment (charlespierce) [reply crates/archive/src/tarball.rs]: That works too 👍 That can be a follow-on issue as well if that’s easier.

Comment (mikrostew) [reply crates/archive/src/tarball.rs]: Went ahead and did it :D

File: crates/fs-utils/Cargo.toml [hunk 2]
```diff
@@ -0,0 +1,8 @@
+[package]
+name = "fs-utils"
+version = "0.1.0"
+authors = ["Michael Stewart <mikrostew@gmail.com>"]
+edition = "2018"
+
+[dependencies]
+failure = "0.1.1"
```
[the remark this answers is not in the document]
Comment (mikrostew) [reply crates/fs-utils/Cargo.toml]: Yeah, missed that
